name: Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      REPORT_GAS: true
      COINMARKETCAP_API_KEY: ${{secrets.COINMARKETCAP_API_KEY}}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Prepare env
        run: cp .env.example .env

      - name: Install dependencies and build
        run: npm ci

      - name: Run tests
        run: make test

      - name: Calculate Solidity contract sizes
        run: make calculate_contract_size

      - name: Run snapshot
        run: NO_COLOR=1 forge snapshot >> $GITHUB_STEP_SUMMARY
